name: BBeeQ

options:
  bundleIdPrefix: com.github.alexgustafsson

targets:
  BBeeQ:
    type: application
    supportedDestinations:
      - macOS
      - iOS
      - ipadOS
    sources:
      - BBeeQ
    deploymentTarget:
      iOS: 18.3
      macOS: 15.5
      ipadOS: 18.6
    settings:
      CODE_SIGN_STYLE: Automatic
      CODE_SIGNING_REQUIRED: YES
      CODE_SIGNING_ALLOWED: YES
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      CODE_SIGN_ENTITLEMENTS: BBeeQ/BBeeQ.entitlements
      SWIFT_VERSION: 5.0
      ENABLE_USER_SCRIPT_SANDBOXING: YES
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_NSBluetoothAlwaysUsageDescription: BBeeQ uses Bluetooth to discover temperature probes.
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation[sdk=iphoneos*]: YES
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation[sdk=iphonesimulator*]: YES
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents[sdk=iphoneos*]: YES
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents[sdk=iphonesimulator*]: YES
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation[sdk=ipados*]: YES
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation[sdk=ipadsimulator*]: YES
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents[sdk=ipados*]: YES
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents[sdk=ipadsimulator*]: YES
      INFOPLIST_KEY_UILaunchScreen_Generation[sdk=iphoneos*]: YES
      INFOPLIST_KEY_UILaunchScreen_Generation[sdk=iphonesimulator*]: YES
      INFOPLIST_KEY_UIStatusBarStyle[sdk=iphoneos*]: UIStatusBarStyleDefault
      INFOPLIST_KEY_UIStatusBarStyle[sdk=iphonesimulator*]: UIStatusBarStyleDefault
      INFOPLIST_KEY_UIStatusBarStyle[sdk=ipados*]: UIStatusBarStyleDefault
      INFOPLIST_KEY_UIStatusBarStyle[sdk=ipadsimulator*]: UIStatusBarStyleDefault
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
    dependencies:
      - target: BBQProbeE
  BBQProbeE:
    type: framework
    supportedDestinations:
      - macOS
      - iOS
      - ipadOS
    sources:
      - BBQProbeE
    deploymentTarget:
      iOS: 18.3
      macOS: 15.5
      ipadOS: 18.6
    settings:
      SWIFT_VERSION: 5.0
      BUILD_LIBRARY_FOR_DISTRIBUTION: YES
      ALLOW_TARGET_PLATFORM_SPECIALIZATION: YES
      GENERATE_INFOPLIST_FILE: YES
